routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\ImageController;

use App\Http\Controllers\FileController;
use App\Http\Controllers\Admin\SliderController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
// Route::get('/create', function () {
//     return view('create');
// });
 
Route::resource('comment', 'App\Http\Controllers\CommentController');
Route::resource('comment', CommentController    ::class);
Route::get('/create', [ImageController::class, 'create']); 

  
// Route::get('/create', [ImageController::class, 'create']); 
// Route::post('/create', [ImageController::class, 'store']);

// Route::get('/create', [FileController::class, 'create']); 
// Route::post('/create', [FileController::class, 'store']);
// Route::get('file', [FileController::class, 'create']); 
// Route::post('file', [FileController::class, 'store']);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');


//CRUD FOR slider
Route::get('/admin/sliderlist', [SliderController::class, 'sliderlist']);
Route::get('/admin/sliderlist/create', [SliderController::class, 'create']);
Route::post('/admin/sliderlist/store', [SliderController::class, 'store']);
Route::get('/admin/deleteslider/{id}',  [SliderController::class, 'deleteslider']);
Route::get('/admin/editslider/{id}',  [SliderController::class, 'editslider']);
Route::post('/admin/updateslider/{id}',  [SliderController::class, 'updateslider']);





// Route::get('/admin/editdoctor/{d_id}', 'Admin\DoctorlistController@editdoctor');
// Route::post('/admin/updatedoctor/{d_id}', 'Admin\DoctorlistController@updatedoctor');


// Route::get('/user', [UserController::class, 'index']);

// Route::get('/admin/sliderlist', 'Admin\SliderController@sliderlist');
// Route::get('/admin/sliderlist/create', 'Admin\SliderController@create');
// Route::post('/admin/sliderlist/store', 'Admin\SliderController@store');
// Route::get('/admin/deleteslider/{id}', 'Admin\SliderController@deleteslider');

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
        'email',
        'comment_line',
    ];

}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use Illuminate\Http\Request;

class CommentController extends Controller
{
  
    public function index()
    {
        $comments = Comment::latest() ->paginate(5);
        return view('comment.index', compact('comments'))
        ->with('i', (request()->input('page', 1)-1) * 5);

        
    }
    

   
    public function create()
    {
       return view('comment.create');
    }

   
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required',
            'comment_line' => 'required'
        ]);

        Comment::create($request->all());

        return redirect()->route('comment.index')
            ->with('success', 'Product created successfully.');

    }
 
    public function show(Comment $comment)
    {
        return view('comment.show', compact('comment'));
    }

   
    public function edit(Comment $comment)
    {
        return view('comment.edit', compact('comment'));
    }
 
    public function update(Request $request, Comment $comment)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required',
            'comment_line' => 'required'
        ]);
        $comment->update($request->all());

        return redirect()->route('comment.index')
            ->with('success', 'comment updated successfully');
    }    

    
    public function destroy(Comment $comment)
    {
        $comment->delete();

        return redirect()->route('comment.index')
            ->with('success', 'comment deleted successfully');
    }
}

resources/views/comment/Index.blade.php
@extends('comment.layout')

@section('content')
    <div class="pull-left">
       <h2> comment section</h2>  
    </div>
    <div class="row">
        <div class="col-lg-12 margin-tb" >
            <div class="pull-right">
                <a class="btn btn-success" href="{{route('comment.create')}}" > new comment</a>
                 </div>
        </div>
    </div>

    
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
                    <p>{{$message}}</p>
        </div>
    @endif
    

    <table class="table table-bordered table-responsive-lg">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th> Email </th>
            <th>Comment</th>
             
            <th width="250px">Actions</th>
        </tr>
        @foreach ($comments as $comment)
            <tr>
                <td>{{++$i}} </td>
                <td>{{$comment->name}}</td>
                <td>{{$comment->email}}</td>
                <td> {{$comment->comment_line}}</td>
                <td>


                    <form action="{{route('comment.destroy', $comment->id) }}" method="POST">

                     <a class="btn btn-info "href="{{route('comment.show', $comment->id) }}" title="show">  Show </a>

                     <a class="btn btn-info "href="{{route('comment.edit', $comment->id) }}" title="show"> Edit  </a>
                 </a>

              @csrf
            @method('DELETE')
            <button type="submit " class="btn btn-danger"> Delete </button>
        </form>
                </td>
            </tr>

@endforeach
    </table>

<div> {{$comments->links()}}</div>
   
@endsection     

resources/views/comment/create.blade.php
@extends('comment.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Comment</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{route('comment.index')}} " title="Go back"> <i class="fas fa-backward "></i> </a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Error!</strong> 
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{$errors }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{route('comment.store')}}" method="POST" >
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Email:</strong>
                    
                        <input type="email" name="email" class="form-control" placeholder="email">

                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Comment:</strong>
                    <textarea class="form-control" style="height:50px" name="comment_line"
                    placeholder="comment"></textarea>                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/comment/edit.blade.php
@extends('comment.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Comment</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{route('comment.index')}}" title="Go back"> <i class="fas fa-backward "></i> </a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Error!</strong> 
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{$errors }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{route('comment.update', $comment->id) }}" method="POST" >
        @csrf
@method('PUT')
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value =" {{$comment->name}}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Email:</strong>
                    
                        <input type="email" name="email" value =" {{$comment->email}}"  class="form-control" placeholder="email">

                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Comment:</strong>
                    <input class="form-control" style="height:50px" value =" {{$comment->comment_line}}" name="comment_line"
                    placeholder="comment">               </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/comment/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">

    <title>Comment Section</title>
     <!-- Font Awesome JS -->
     <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
     integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous">
 </script>
 <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous">
 </script>
  <style>
    .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: #9C27B0;
        color: white;
        text-align: center;
    }

</style>
</head>
<body>
    
</body>
<div class="container">
@yield('content')
</div>
</html>

resources/views/comment/show.blade.php
@extends('comment.layout')